### ISSUE TITLE
Django 1.8 Warnings

### ISSUE THREAD

**Issue by cerealcable** [hatchrbr/django-alacarte#8]
Worked on upgrading to Django 1.8 and saw the following warning:
> RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.

Ended up getting a stacktrace and it showed me that its being used by django-alacarte. Certainly this isn't a huge issue, but would be nice to get rid of a warning by using the new methods in Django 1.8. Below is a stacktrace (you can get this by running python -W "error:django.utils.importlib:DeprecationWarning" manage.py).

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/cerealcable/PycharmProjects/project/venv/lib/python3.4/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/cerealcable/PycharmProjects/project/venv/lib/python3.4/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/home/cerealcable/PycharmProjects/project/venv/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/cerealcable/PycharmProjects/project/venv/lib/python3.4/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/cerealcable/PycharmProjects/project/venv/lib/python3.4/site-packages/django/apps/config.py", line 86, in create
    module = import_module(entry)
  File "/home/cerealcable/PycharmProjects/project/venv/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2231, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2203, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1448, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/cerealcable/PycharmProjects/project/venv/lib/python3.4/site-packages/alacarte/__init__.py", line 8, in <module>
    from django.utils.importlib import import_module
  File "/home/cerealcable/PycharmProjects/project/venv/lib/python3.4/site-packages/django/utils/importlib.py", line 9, in <module>
    RemovedInDjango19Warning, stacklevel=2)
django.utils.deprecation.RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
```

As always, thanks for such a fantastic project! If I get enough time to work on this I'll submit a pull request, though at the moment I just wanted to at least document this.

**Comment by mstrcnvs** [comment]
Hi thanks for the feedback!
Didn't use `django-alacarte` with Django 1.8 yet.

Now that Django has `django.utils.module_loading.autodiscover_modules`, which don't use `django.utils.importlib` instead it uses `importlib` directly, guess we can make use that.

**Comment by mstrcnvs** [comment]
Fixed by #10

**Comment by cerealcable** [comment]
Any chance you could publish a release with this fix included? Would be nice for deployment purposes. Maybe v0.1.5.1?

**Comment by mstrcnvs** [comment]
Done @cerealcable!

**Comment by cerealcable** [comment]
Thanks @mstrcnvs, appreciate it!
